main:
  push:
    - name: go-test
      docker:
        image: golang:1.22
      stages:
        - name: test
          script: go test ./... -v

    - name: docker-build
      services:
        - docker
      docker:
        image: golang:1.22
      stages:
        - name: build binary
          script: CGO_ENABLED=0 GOOS=linux go build -o tinygate .
        - name: build and push image
          script: |
            docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
            docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest

  pull_request:
    - name: go-test
      docker:
        image: golang:1.22
      stages:
        - name: test
          script: go test ./... -v
